config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #homesコントローラー
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'

  #recipeコントローラー(favoritesとreviewsはネストする)
  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    resources :reviews
  end

  #userコントローラー
  get '/users/mypage' => 'users#show', as: 'mypage'
  get '/users/index/:id' => 'users#other_user', as: 'other_user'#deviseのルーティングと被るためindexの文字をかませた
  get '/users' => 'users#index', as: 'users_index'
  get '/users/edit/data' => 'users#edit', as: 'users_edit' #edit_user_registration_pathとURLがかぶるため/customers/edit→/customers/edit/dataに変更
  #patch 'users' => 'users#update', as: 'users_update' usersにネストしたいルーティングあるので
  get '/users/check' => 'users#check', as: 'users_check'
  delete '/users/withdrawal' => 'users#withdrawal', as: 'users_withdrawal'
  get '/users/search/' => 'users#search', as: 'search'#検索用

  resources :users, only: [:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end


  devise_for :users
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :how_to_makes, dependent: :destroy
  has_many :recipe_ingredients, dependent: :destroy

  accepts_nested_attributes_for :recipe_ingredients, :how_to_makes, allow_destroy: true
  #accepts_nested_attributes_forを使用することで、指定したモデルのデータを配列としてパラメーターに含めることができる。
  #つまり、「recipe」と「recipe_ingredients」「how_to_makes」モデルのデータをまとめて保存できるようになる。
  #allow_destroy: true　→　意味はaccepts_nested_attributes_forを使用した際に dependent: :destroyと同じ意味・役割を持つ

  attachment :dish_photo

  validates :dish, presence: true#存在しますか
  validates :time, presence: true#存在しますか
  validates :money, presence: true#存在しますか

  def favorited_by?(user)#ここの書き方を後で復習→OK
    favorites.where(user_id: user.id).exists?
  end
  #favoritesテーブルの中のuser_idの中にuser.idがいたらtrueを返すの記述
  #()の記述で引数を設定する.あくまで大事のは()の引数入力欄を準備してあげること．ここが対応する．favorited_by?の記述はなんでも良い．
  #(user)→(current_user)とすることでdefの中身のuser.idがcurrent_user_idの記述になる
  #user_idはfavoritesテーブルの中の探したいカラム名なのでこっちは変わらない

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
    @recipe_ingredients = @recipe.recipe_ingredients.build #親モデル.子モデル.buildで子モデルのインスタンス作成(.newで、子モデル用に作成する感じ)
    @how_to_makes = @recipe.how_to_makes.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
    #recipe_ingredientsとhow_to_makesはviewで記述はないが他のモデルのパラメータを同時に保存できている

    if @recipe.save
      redirect_to recipe_path(@recipe.id)
    else
      #@recipe = Recipe.new
      #@recipe_ingredients = @recipe.recipe_ingredients.build
      #@how_to_makes = @recipe.how_to_makes.build
      #上3行の記述があると失敗するたびにフォームの入力内容が消去される

      render :new
      #renderのみであれば失敗しても失敗した時の入力データは残る
    end
  end

  def show
    @recipe = Recipe.find(params[:id])

    #レシピ詳細ページでユーザー情報の受け渡し用(フォロー機能で必要)
    @user = User.find(@recipe.user_id)

    @review = Review.new

    #詳細画面で該当するレビューをすべて表示させる
    @reviews = Review.where(recipe_id: @recipe.id)
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(recipe_params)
     #recipeとアソシエーションを組んでいるhow_to_makeやrecipe_ingredientsのデータもrecipe_paramsに含まれているため一緒に紐づいているデータも含めて更新される。

    #updateももし一つずつデータを更新するなら↓↓↓こうも書ける
    # @recipe.time = params[:recipe][:time]
    # @recipe.money = params[:recipe][:money]
    # @recipe.dish_photo_id = params[:recipe][:dish_photo_id]
    # @recipe.recipe_ingredients.find(params[:recipe][:recipe_ingredients_attributes][0][:id]).material = params[:recipe][:recipe_ingredients_attributes][0][:material]
    # @recipe.recipe_ingredients.find(params[:recipe][:recipe_ingredients_attributes][0][:id]).quantity = params[:recipe][:recipe_ingredients_attributes][0][:quantity]
    # @recipe.recipe_ingredients.find(params[:recipe][:recipe_ingredients_attributes][0][:id]).material = params[:recipe][:recipe_ingredients_attributes][0][:material]
    # @recipe.recipe_ingredients.find(params[:recipe][:recipe_ingredients_attributes][0][:id]).quantity = params[:recipe][:recipe_ingredients_attributes][0][:quantity]
    # @recipe.update
    #ここまで。ただし，recipe_ingredientsやhow_to_makesの記入数が固定されてしまうので現実的ではない。

    redirect_to recipe_path(@recipe.id)
  end

  def index
     @recipes = Recipe.page(params[:page]).per(9)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to mypage_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:user_id, :time, :money, :dish_photo, :dish,
                                  recipe_ingredients_attributes:[:id, :material, :quantity, :_destroy],
                                  how_to_makes_attributes:[:id, :introduction, :order_no, :_destroy])
  end
end

#recipe_ingredients_attributes:の記述の仕方
#recipeモデルアソシエーションが複数ならrecipe_ingredients(複数形)で記述．_attributesはいつでも複数形。
#:idもrecipe_ingredientのデータを，どのデータで上書きしたらいいか判断するために必要
#:_destroyは削除用のボタンの記述

#cocoonのgemによってストロングパラメータのpermit内のrecipe_ingredients_attributes:の_attributes:記述で
#belongs_to recipeの記述によって外部キー（今回はrecipe_id）を送ってくれる記述におそらくなっている。

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_how_to_make_fields.html.erb
<div class="nested-fields">
  <div class="row mx-auto">
    <div class="col-2">
      <%= f.text_field :order_no, class: "form-control", placeholder: "順番" %>
    </div>

    <div class="offset-1 col-6">
      <%= f.text_area :introduction, class: "form-control", placeholder: "調理手順" %>
    </div>
    <%= f.hidden_field :id %>
    <div class="offset-1 col-2 px-0">
      <%= link_to_remove_association "削除", f, class: "btn btn-secondary btn-block" %>
    </div>
  </div>
</div>

app/views/recipes/_recipe_ingredient_fields.html.erb
<div class="nested-fields">
  <div class="row mx-auto">
    <div class="col-4">
      <%= f.text_field :material, class: "form-control", placeholder: "材料" %>
      <!--渡されたfに入力欄を作成する(データの内容はmaterialカラム)-->

      <!--f.hidden_fieldのようにvalueは記載されてはいないが実際は-->
      <%#= f.text_field :material, class: "form-control", placeholder: "材料", value: f.materialカラムに入っていたデータ %>
      <!--のように裏で動いている-->
    </div>

    <div class="offset-1 col-3">
      <%= f.text_field :quantity, class: "form-control", placeholder: "分量" %>
    </div>
    <%= f.hidden_field :id %>
    <!--valueを指定しない場合は指定したモデルの該当するカラムのデータが入力される。今回はrecipe_ingredientモデルのidカラムが該当。書くなら下のようになる-->
    <%#= f.hidden_field :id, value: f.id %>

    <div class="offset-1 col-2 px-0">
      <%= link_to_remove_association "削除", f, class: "btn btn-secondary btn-block" %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container">
  <h4 class="mt-3 mb-3">レシピ編集</h4>
  <div class="recipe-post">
    <%= form_with model: @recipe, url: recipe_path(@recipe.id), local: true do |f| %>
      <div class="row">
        <div class="col-lg-5">
          <%= f.text_field :dish, class: "form-control mb-3", placeholder: "料理名" %>
          <br>写真の拡張子はjpegに限ります</br>
          <%= f.attachment_field :dish_photo, class: "mb-3" %><!--dish_photo_idのidは省略．写真投稿用-->
          <%= f.text_field :time, class: "form-control mb-3", placeholder: "所要時間" %>
          <%= f.text_field :money, class: "form-control mb-3", placeholder: "費用" %>

        </div>
      </div>

<!--①レシピ材料入力欄．ここから-->
      <div class="row mt-3">
        <div class="recipe-ingredients">
          <div class="mx-auto">

            <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
        <!--fields_forによってform_with内で異なるモデル（今回は:recipe_ingredients）を編集することができるようになる。-->

        <!--@recipeに紐づいている:recipe_ingredientsでデータをすべて取得してrecipe_ingredientに1レコードずつ入れて表示-->
        <!--_forはeachと似たような処理(繰り返し処理をする)。やっていることはeach同様全レコードデータのうち1レコードずつ値を入れて処理内容を実施．-->

              <%= render "recipes/recipe_ingredient_fields", f: recipe_ingredient %>
              <!--f: t　ｆは部分テンプレートで使う変数。t(今回はrecipe_ingredienにして入力)は部分テンプレートに渡す変数．-->
              <!--fの中にrecipe_ingredient。つまりf = recipe_ingredient。これをrenderしている部分テンプレートに渡して処理をする-->
            <% end %>

          </div>

          <div id="detail-association-insertion-point1"></div>

          <div class="col-lg-10 mx-auto mt-3">

            <%= link_to_add_association "+フォームを追加", f, :recipe_ingredients,
            class: "btn btn-secondary btn-block",
            data: {
            association_insertion_node: '#detail-association-insertion-point1',
            association_insertion_method: 'before'
            }%>
        <!--link_to_add_associationによってフォームが追加される。-->

        <!--association_insertion_node: '#detail-association-insertion-point'
            association_insertion_method: 'after'
            によってフォームの表示位置を指定。-->
          </div>
        </div>
      </div>
<!--①レシピ材料入力欄．ここまで-->

<!--①レシピ調理方法入力欄．ここから-->
      <div class="row mt-3">
        <div class="how-to-makes">
          <div class="mx-auto">

            <%= f.fields_for :how_to_makes do |t| %>
        <!--fields_forによってform_with内で異なるモデル（今回はHowToMake）を編集することができるようになる。-->
        <!---->
              <%= render "recipes/how_to_make_fields", f: t %>
            <% end %>

          </div>

          <div id="detail-association-insertion-point2"></div>

          <div class="col-lg-10 mx-auto mt-3">

            <!--link_to_add_association "+フォームを追加", f, :how_to_makes,のhow_to_makesの意味→空のインスタンスを作成する。アソシエーションの記述の仕方で記入する-->
            <!--アソシエーションで複数系になっているのでこっちも複数形で書く-->
            <%= link_to_add_association "+フォームを追加", f, :how_to_makes,
            class: "btn btn-secondary btn-block",
            data: {
            association_insertion_node: '#detail-association-insertion-point2',
            association_insertion_method: 'before'
            }%>
        <!--link_to_add_associationによってフォームが追加される。-->
        <!--association_insertion_node: '#detail-association-insertion-point'
            association_insertion_method: 'after'
            によってフォームの表示位置を指定。-->
          </div>
        </div>
      </div>
<!--①レシピ調理入力欄．ここまで-->
      <br><%= f.submit '編集完了', class: "mt-3 btn btn-primary" %></br>
    <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row">
     <% @recipes.each do |recipe| %>
      <div class="col-lg-4">
        <div>
          <%= link_to recipe_path(recipe.id) do %>
            <%= attachment_image_tag recipe, :dish_photo, format: 'jpeg', size: "300x300", fallback: "no_image.jpg", size:'300x300', class: "mb-3" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <%= paginate @recipes %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">

<!--エラーメッセージ-->
  <div class="row">
    <% if @recipe.errors.any? %>
      <div class = "alert">
        <ul>
          <% @recipe.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
<!--エラーメッセージここまで-->

  <h4 class="mb-3">レシピ投稿</h4>
  <div class="recipe-post">
    <%= form_with model: @recipe, url: recipes_path, local: true do |f| %>
      <div class="row">
        <div class="col-lg-5">
          <%= f.text_field :dish, class: "form-control", placeholder: "料理名" %>
          <br>写真の拡張子はjpegに限ります</br>
          <%= f.attachment_field :dish_photo, class: "mb-3" %><!--dish_photo_idのidは省略．写真投稿用-->
          <%= f.text_field :time, class: "form-control mb-3", placeholder: "所要時間(例:〇〇分)。分まで入力" %>
          <%= f.text_field :money, class: "form-control mb-3", placeholder: "費用(日本円金額のみ入力)" %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        </div>
      </div>

<!--①レシピ材料入力欄．ここから-->
      <div class="row mt-3">
        <div class="recipe-ingredients">
          <div class="mx-auto">

            <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
        <!--fields_forによってform_with内で異なるモデル（今回は:recipe_ingredients）を編集することができるようになる。-->

        <!--@recipeに紐づいている:recipe_ingredientsでデータをすべて取得してrecipe_ingredientに1レコードずつ入れて表示-->
        <!--_forはeachと似たような処理(繰り返し処理をする)。やっていることはeach同様全レコードデータのうち1レコードずつ値を入れて処理内容を実施．-->

              <%= render "recipes/recipe_ingredient_fields", f: recipe_ingredient %>
              <!--f: t　ｆは部分テンプレートで使う変数。t(今回はrecipe_ingredienにして入力)は部分テンプレートに渡す変数．-->
              <!--fの中にrecipe_ingredient。つまりf = recipe_ingredient。これをrenderしている部分テンプレートに渡して処理をする-->
            <% end %>

          </div>

          <div id="detail-association-insertion-point1"></div>

          <div class="col-lg-11 mx-auto mt-3">

            <%= link_to_add_association "+フォームを追加", f, :recipe_ingredients,
            class: "btn btn-secondary btn-block",
            data: {
            association_insertion_node: '#detail-association-insertion-point1',
            association_insertion_method: 'before'
            }%>
        <!--link_to_add_associationによってフォームが追加される。-->

        <!--association_insertion_node: '#detail-association-insertion-point'
            association_insertion_method: 'after'
            によってフォームの表示位置を指定。-->
          </div>
        </div>
      </div>
<!--①レシピ材料入力欄．ここまで-->

<!--①レシピ調理方法入力欄．ここから-->
      <div class="row mt-3">
        <div class="how-to-makes">
          <div class="mx-auto">

            <%= f.fields_for :how_to_makes do |t| %>
        <!--fields_forによってform_with内で異なるモデル（今回はHowToMake）を編集することができるようになる。-->
        <!---->
              <%= render "recipes/how_to_make_fields", f: t %>
            <% end %>

          </div>

          <div id="detail-association-insertion-point2"></div>

          <div class="col-lg-11 mx-auto mt-3">

            <!--link_to_add_association "+フォームを追加", f, :how_to_makes,のhow_to_makesの意味→空のインスタンスを作成する。アソシエーションの記述の仕方で記入する-->
            <!--アソシエーションで複数系になっているのでこっちも複数形で書く-->
            <%= link_to_add_association "+フォームを追加", f, :how_to_makes,
            class: "btn btn-secondary btn-block",
            data: {
            association_insertion_node: '#detail-association-insertion-point2',
            association_insertion_method: 'before'
            }%>
        <!--link_to_add_associationによってフォームが追加される。-->
        <!--association_insertion_node: '#detail-association-insertion-point'
            association_insertion_method: 'after'
            によってフォームの表示位置を指定。-->
          </div>
        </div>
      </div>
<!--①レシピ調理入力欄．ここまで-->
      <br><%= f.submit 'レシピ投稿', class: "mt-3 btn btn-primary" %></br>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<!--review用メッセージ-->
<div><%= flash[:reviewalert] %></div>
<div><%= flash[:reviewnotice] %></div>
<!--終わり-->

<div class="container">
  <div class="row">
    <div class="col-lg-12">

      <div style="font-size: 25px;">
        レシピ名:<%= @recipe.dish %>
      </div>

      <div>
        <%= attachment_image_tag @recipe, :dish_photo, format: 'jpeg', size: "300x300", fallback: "no_image.jpg", size:"300x300" %>
      </div>

      <div>
        所要時間:<%= @recipe.time %>
      </div>

      <div>
        費用:<%= @recipe.money %>円
      </div>

    </div>
  </div>

  <!--材料表記-->
  <div class="row">
    <table class="table table-bordered" style="width:400px;">
      <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
        <tr class="bg-white">

          <td>
            <%= recipe_ingredient.material %>
          </td>

          <td>
            <%= recipe_ingredient.quantity %>
          </td>

        </tr>
      <% end %>
    </table>
  </div>

<!--調理手順表記-->
  <% @recipe.how_to_makes.each do |how_to_make| %>
    <div class="row">
      <%= how_to_make.order_no %>.<%= how_to_make.introduction %>
    </div>
  <% end %>

<!--いいね機能-->
  <div class="favorite row">
    <% if user_signed_in? %>

      <% if @recipe.favorited_by?(current_user) %>
        <div>
          <%= link_to recipe_favorites_path(@recipe.id), method: :delete do %>
            ♥<%= @recipe.favorites.count %> いいね
          <% end %>
        </div>
        <% else %>
        <div>
          <%= link_to recipe_favorites_path(@recipe.id), method: :post do %>
            ♡<%= @recipe.favorites.count %> いいね
          <% end %>
        </div>
      <% end %>

    <% end %>
  </div>
<!--いいね機能終わり-->

  <!--フォロー部-->
  <% if user_signed_in? %>
    <% if current_user.id != @recipe.user_id %>
      <div class="row">
        <% if @user.followed_by?(current_user) %>
          <p><%=link_to "フォロー解除", user_relationships_path(@recipe.user_id), method: :delete, class: "btn btn-danger" %></p>
        <% else %>
          <p><%=link_to "フォローする", user_relationships_path(@recipe.user_id), method: :post, class: "btn btn-primary" %></p>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <!--フォロー部終わり-->

  <% if user_signed_in? %>
    <div class="row">
      <% if @recipe.user_id == current_user.id %>
        <%= link_to "編集する", edit_recipe_path(@recipe.id), class: "mt-3 mb-5 btn btn-success" %>
        <%= link_to "削除する", recipe_path(@recipe.id), method: :delete, class: "mt-3 ml-3 mb-5 btn btn-danger" %>
      <% end %>
    </div>
  <% end %>

<!--review作成画面-->
  <% if user_signed_in? %>

    <% if @recipe.user_id != current_user.id %>

      <% if @recipe.reviews.exists?(user_id: current_user.id) %>
        <div class="review-complete" style="color:blue;">レビュー済みです</div>
      <% else %>
        <div class="review-box">
          <%= form_with model:[@recipe, @review],url: recipe_reviews_path(@recipe.id), local: true  do |f| %>
<!--ネストしている場合はreviewに紐づいているreviewに投稿するのでモデル部に[@review, @review]で記述-->

<!--質問：postメソッドだが，ネストしており、urlにrecipe_idの記載があるためidを渡す必要がある？？？→あるっぽい-->


  <!--エラーメッセージ-->
  <%#= render 'layouts/error_messages', model: f.object %>
  <!--エラーハンドリングという内容を調べる-->

  <!--商品コードの送信-->
            <%= f.hidden_field :recipe_id, value: @recipe.id %>

<!--review★マーク機能はここから-->
  <!-- 評価 -->
            <div class="row form-group" id="star">
              <%= f.label :score,'評価 ', class:'col-lg-3 col-form-label' %>
              <%= f.hidden_field :score, id: :review_star %>
            </div>

  <!-- 評価javascript -->
            <script>
              $('#star').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                scoreName: 'review[score]',
                half: true,
              });
            </script>
  <!--scoreNama: 'モデル[カラム]'で記述して記載-->
  <!--どこのカラムを使用して★マークを表示させたいか-->
  <!--ここまでで1セット-->

  <!-- 口コミ -->
            <div class="row form-group">
              <%= f.label :comment, '口コミ内容 ', class:'col-md-3 col-form-label' %>
              <div class="col-md-9">
                <%= f.text_area :comment, class: "form-control", rows: "5", placeholder:'口コミ内容がなくても、タイトルと評価のみで投稿できます。まずは投稿してみましょう！投稿してから編集もできますよ！' %>
              </div>
            </div>

  <!-- 確認ボタン -->
            <div class="row form-group justify-content-end">
              <div class="col-lg-9">
                <%= f.submit '投稿する', class:"btn btn-success" %>
              </div>
            </div>

          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<!--ここまでレビュー用-->

<!--レビュー一覧を表示-->
  <div class="row mt-5" style="font-size: 25px;">レビュー一覧</div>
  <div class="review-index">
    <% if @reviews.present? %>
      <% @reviews.each do |review| %>
        <div class="row">
          <div class="col-md-6 mb-3">
            <div>
              <p><%= simple_time(review.created_at) %></p>
              <h4 class="mb-3">評価：<%= review.score %>点</h4>

          <!--星評価-->
             <div id="star-rate-<%= review.id %>" class="star-size"></div>
              <script>
              $('#star-rate-<%= review.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= review.score %>,
              });
              </script>
        <!--/星評価-->

              <p><%= review.comment %></p>
            </div>
          </div>

          <div class="col-lg-12">
            <% if user_signed_in? %>
              <% if current_user.id == review.user_id %>
                <%= link_to "レビューを編集", edit_recipe_review_path(@recipe.id, review.id), class: "btn btn-success" %>
                <%= link_to "レビューを削除", recipe_review_path(@recipe.id, review.id), method: :delete, class: "btn btn-danger" %>
              <% end %>
            <% end %>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>