config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #homesコントローラー
  root to: 'homes#top'
  get '/about' => 'homes#about', as: 'about'

  #recipeコントローラー(favoritesとreviewsはネストする)
  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    resources :reviews
  end

  #userコントローラー
  get '/users/mypage' => 'users#show', as: 'mypage'
  get '/users/index/:id' => 'users#other_user', as: 'other_user'#deviseのルーティングと被るためindexの文字をかませた
  get '/users' => 'users#index', as: 'users_index'
  get '/users/edit/data' => 'users#edit', as: 'users_edit' #edit_user_registration_pathとURLがかぶるため/customers/edit→/customers/edit/dataに変更
  #patch 'users' => 'users#update', as: 'users_update' usersにネストしたいルーティングあるので
  get '/users/check' => 'users#check', as: 'users_check'
  delete '/users/withdrawal' => 'users#withdrawal', as: 'users_withdrawal'
  get '/users/search/' => 'users#search', as: 'search'#検索用

  resources :users, only: [:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end


  devise_for :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true#存在しますか
  #emailのバリデーションは既に準備されていた(おそらくdevise側)


  has_many :recipes, dependent: :destroy
  #シンボルとは
  #:〇〇が付く文字列。内部で数字で保存されている。

  #第一引数でrecipes。第2引数でdependent: :destroyが入る。
  #メソッドの最後の引数に{}が必要な記述がある場合にはそれは省略できる。
  #{キー: :値(シンボルのこと)}。has_manyのメソッドでこの内容を要求している。
  #{dependent: :destroy}→dependent: :destroyに省略可能
  #ハッシュの記述の仕方として{:太郎=>185}→{太郎: 185}が現在ではよく使われている。
  #シンボルはPC側から見たら容量が軽いため、動作が軽くなるためこの形で管理されている。
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy



  #フォロー機能
  #フォローする側のUserからみたRelationship(中間テーブル)をactive_relationship
  #フォローされる側のUserからみたRelationship(中間テーブル)をpassive_relationship
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  #active_relationshipsは現時点では無いためここで定義。中間テーブルはRelationshipモデルでることを設定。
  #relaitonshipsテーブルにアクセスする時、following_idを入口として来てね！」っていう事

  has_many :followings, through: :active_relationships, source: :follower
  #through: :active_relationshipsはactive_relationshipsが中間テーブルであると設定
  #ここのfollowingsはfollowingの複数形だがフォローする側の人から見たフォローしている人達のことをfollowingと定義(元々無い)。
  #アソシエーションのhas manyの後ろに来るのでfollowingsと記述
  #relationshipモデルに記述したfollowingとは意味が違うので気を付けること!関係ないよ！

  #source: :follower
  #「relationshipsテーブルのfollower_idを参考にして、followingsモデルにアクセスしてね」って事。
  #結果として、user.followings と打つだけで、user が中間テーブル relationships を取得し、
  #その1つ1つの relationship のfollowing_idから、「フォローしている User 達」を取得することができる。

  #下のように覚える
  #foregin_key = 入口とする外部キー
  #source = 出口とする外部キー(_idは省略)

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following


  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    #簡潔に言うとフォロー済みですか？メソッド
    passive_relationships.find_by(following_id: user.id).present?
  end
  #--ここまで--

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show#マイページ用
    @user = current_user
    @recipes = current_user.recipes#ログインユーザーの全投稿レシピ取得
  end

  def other_user#他のユーザーのマイページ用
    @user = User.find(params[:id])
    @recipes = @user.recipes#他ユーザー投稿レシピを全て取得
  end


  def index
    @users = User.all
  end


  def edit
    @user = current_user
  end

  def update
    user = User.find_by(email: current_user.email)
    user.update(user_params)
    redirect_to mypage_path
  end

  def check

  end

  def withdrawal
    @user = current_user
    @user.destroy
  end

  def search#部分一致による検索(user名)
    if params[:user].present? && params[:user][:name].present?
      #params[:user].present?
      #params[:user] == nilが返されるためfalseが出力される。（nil.present?となるため当然false）
      #A && Bの論理演算子はAがfalseの場合Bは見ないためAしか判断されない。Aがtrueの時のみBを実行して比較する。
      #params[:user][:name].present?はnil[:name].present?となりなにを見るか分からないためnomethodエラーになる。
      #なのでparams[:user]がある時のみ検索をかける場合は上記の記述になる。

      @users = User.where('name LIKE ?', "%#{params[:user][:name]}%")
      #name LIKEと書くことでnameカラムを検索、という意味
      #?は次の引数"%#{params[:name]}%"を受け取る場所
      #最終的にはname LIKE "%#{params[:name]}%"となる
      # %文字% は任意の文字列
      #結果としてはnameカラムにparams[:name]を含むレコードを探し出す
      ##{params[:name]}は変数展開

      #Parametersはuser"=>{"name"=>"bbb"}の形で飛ばしているので，受け取るときはparams[:user][:name]で記述。

    else
      @users = User.none
    end

    if params[:recipe].present? && params[:recipe][:dish].present?
      @recipes = Recipe.where('dish LIKE ?', "%#{params[:recipe][:dish]}%")

    else
      @recipes = Recipe.none
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers

  end

  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/check.html.erb
<div class="container">
  <div class="row">
    <div class=" text-box col-lg-12 mx-auto text-center">
      退会すると今まで投稿してきたレシピは削除されます。
      <br>本当によろしいですか？</br>
      <br>
        <%= link_to "退会する", users_withdrawal_path, method: :delete, "data-confirm" => "本当に退会しますか？", class: "mt-3 btn btn-danger" %>
        <%= link_to "まだ利用する", root_path, class: "mt-3 ml-3 btn btn-primary" %>
      </br>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
 <h4>会員情報編集</h4>
    <%= form_with model: @user, url: user_path(current_user.id), local:true do |f| %>
    <table class="table table-borderless mt-3">
      <tr>
        <td>
          会員ID
        </td>
        <td>
          <%= @user.id %>
        </td>
      </tr>

      <tr>
        <td>
          名前
        </td>
        <td>
           <%= f.text_field :name %>
<!--メソッドは2種類ある-->
<!--インスタンスメソッドとクラスメソッドがある-->
<!--インスタンスメソッドをこちらは実行されている。.nameでインスタンス変数のnameカラムが出力されるなど-->
<!--扱うデータによってどちらで実行されるか決まる。-->
<!--変数.nameの変数の違い（文字が異なるではない）によって左右される-->
<!--データの取得の結果によって決まる。-->
<!--@userはusersテーブルの中の1レコード分のデータ-->
<!--searchのviewの@usersはusersテーブルの中にあるある条件に合致するすべてのデータを参照する-->
<!--これにより変化する。1行（レコード）or条件に合致するすべての行を取得するか-->
<!--ある1行のデータに対して行われるメソッドがインスタンスメソッド-->
<!--条件に合致する全ての行に対して行われるメソッドがクラスメソッド-->
<!--どのデータのカラムを参照するかが明確な場合はインスタンスメソッド(1行のデータを取得しているため明確)-->

<!--例-->
<!--users = User-->
<!--users.age-->
<!--NomethodErrorが起きる。ageというクラスメソッドが実行されようとするがそんなものはないためエラーが起きる-->

<!--users.name-->
<!--users.nameはインスタンス変数での.nameというメソッドもあるがusersが条件に合致するすべての行を取得しようとしていた（実際複数かどうかは関係ない）-->
<!--データなのでクラスメソッドが実行される。その結果nameカラムが表示されず、user.rbのclass名が表示-->
        </td>
      </tr>

      <tr>
        <td>
          メールアドレス
        </td>
        <td>
           <%= f.text_field :email %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.submit '編集内容を保存', class: "mt-3 btn btn-success" %>
        </td>
      </tr>
    </table>
    <% end %>
</div>

<!--ボタンを押してもエラーも出ない場合は，そもそも機能していない(HTMLの構造がおかしい)ので検証ツールを用いて確認する-->
<!--formの中にinputがあるかなどを確認する。-->
<!--tableタグとformは相性が悪い。tableタグはほかの要素と共存できない（入るデータが決まっている(tdなど)）ことがあるため注意-->
<!--tableタグの中にformがあると不具合が起きるのでtableの外に配置する．文法は間違っていないので注意．-->

app/views/users/followers.html.erb
<div class="container">
  <div class="row">

    <h1>フォロワー一覧</h1>

    <% @users.each do |user| %>
      <table class="table table-bordered mt-3">
        <tr>
          <td>
            会員ID
          </td>
          <td>
            <%= user.id %>
          </td>
        </tr>

        <tr>
          <td>
            名前
          </td>

          <td>
            <%= user.name %>
          </td>

          <td>
            <% if current_user.id != user.id %>
              <% if user.followed_by?(current_user) %>
                <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %>
              <% else %>
                <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-primary" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="container">
  <div class="row">

    <h1>フォロー一覧</h1>

    <% @users.each do |user| %>
      <table class="table table-bordered mt-3">
        <tr>
          <td>
            会員ID
          </td>
          <td>
            <%= user.id %>
          </td>
        </tr>

        <tr>
          <td>
            名前
          </td>

          <td>
            <%= user.name %>
          </td>

          <td>
            <% if current_user.id != user.id %>
              <% if user.followed_by?(current_user) %>
                <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %>
              <% else %>
                <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-primary" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">

 <!--会員一覧-->
  <div class="col-8 mx-auto">
  <h3>会員一覧</h3>

   <table class="table table-hover">
     <thead><!--表のヘッダー-->
       <tr>
        <th class="header1 text-center">会員ID</th>
        <th class="header2 text-center">氏名</th>
        <% if user_signed_in? %>
          <th class="header3"></th><!--空.テーブル作成用-->
        <% end %>
       </tr>
     </thead>

     <tbody><!--会員ごとのデータをtableで並べていく-->
      <% if user_signed_in? %>

        <% @users.each do |user| %>
          <% if current_user.id != user.id %>
            <tr class="text-center">
              <td><%= user.id %></td><!--会員IDのデータ-->

              <td><!--氏名のデータ-->
                <%= link_to other_user_path(user.id) do %>
                  <%= user.name %>
                <% end %>
              </td>

              <td><!--フォロー機能-->
                <% if user.followed_by?(current_user) %>
                    <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %>
                  <% else %>
                    <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-primary" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>

        <% else %>
          <% @users.each do |user| %>

            <tr class="text-center">
              <td>
                <%= user.id %>
              </td><!--会員IDのデータ-->

              <td><!--氏名のデータ-->
                <%= link_to other_user_path(user.id) do %>
                  <%= user.name %>
                <% end %>
              </td>
            </tr>
          <% end %>
      <% end %>
     </tbody>

   </table>

  </div>
</div>

app/views/users/other_user.html.erb
<div class="container">
  <div class="row"  style="width:350px;">
    <table class="table table-bordered mt-3">
      <tr>
        <td>
          会員ID
        </td>
        <td>
          <%= @user.id %>
        </td>
      </tr>

      <tr>
        <td>
          名前
        </td>
        <td>
          <%= @user.name %>
        </td>
      </tr>
    </table>
  </div>

  <% if user_signed_in? %>
    <div class="row">
      <% if @user.followed_by?(current_user) %>
        <p><%=link_to "フォロー解除", user_relationships_path(@user.id), method: :delete, class: "btn btn-danger" %></p>
        <% else %>
          <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-primary" %></p>
      <% end %>
    </div>
  <% end %>

  <div class="row mt-3">
    <% @recipes.each do |recipe| %>
      <div class="col-lg-4">
        <%= link_to recipe_path(recipe.id) do %>
          <%= attachment_image_tag recipe, :dish_photo, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg", size:'300x300' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<div class="container">
  <div class="row">
    <h3>ユーザー検索フォーム</h3>
  </div>

  <div class="row">
    <%#= @users.inspect %>
    <!--変数の中身を出力-->
    <!--#<ActiveRecord::Relation []>。取得できる値は無いが、#<ActiveRecord::Relation []>というデータがいる状態-->

    <%#= @users.class %>
    <!--@usersに入っているデータのclass-->
    <!--classは定数のこと-->
    <!--定数:大文字で始まる識別子。Rubyの定数の概念を知ること！左辺の大文字から始まる入れ物-->
    <!--Hoge=1,Hogeは定数-->
    <!--@users.classでUser::ActiveRecord_Relationが出力される-->
    <!--ApplicationRecordというclassにActiveRecord_Relationが付随している。なのでApplicationRecordが親に当たる。-->
    <!--なのUser::ActiveRecord_RelationはApplicationRecordのことなので@users.classと打つとUser::ActiveRecord_Relationが出力される-->
    <!--class User < ApplicationRecord(user.rbに記載されている)はUserというclassにApplicationRecordというclass(機能)を持たせている-->
    <!--ApplicationRecordでRailsの機能を使えるようにしている-->
    <!--gem railsがbundle installされている状態という前提で記述されている。-->
    <!--例えばこんな機能を提供してくれている。all,find,find_by,whereなど-->

    <%#= @users.name %>
    <!--@usersのclass名を参照-->
    <!--@users.classはclassを出力，@users.nameはclass名を出力。違うものなので注意すること-->

    <%= form_with model: @users, url: search_path, method: :get, local: true do |f| %>
    <!--保存しない(getによるページの遷移のみ)ので、モデルの記述が無くてもフォームは作成できる-->
    <!--そのため.nameがクラスメソッドになってしまうのを防ぐことができる-->

      <%= f.text_field :name, placeholder:'名前', value:"" %><!--value:""で初期値の入力を設定-->
      <%= f.submit '検索' %>
    <% end %>
  </div>
    <div class="row">
      <table>
        <thead>
          <tr>
            <th>ユーザー名検索結果一覧</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %><!--ログイン時-->
            <% if user_signed_in? %>
              <% if current_user.id != user.id %><!--ログインユーザーを除外-->
                <tr>
                  <td>
                    <%= link_to other_user_path(user.id) do %>
                      <%= user.name %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% else %><!--未ログインユーザー-->
              <tr>
                <td>
                  <%= link_to other_user_path(user.id) do %>
                    <%= user.name %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

  <div class="row" style="margin-top:100px;">
    <h3 >レシピ検索フォーム</h3>
  </div>

  <div class="row">
    <%= form_with model: @recipes, url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :dish, placeholder:'料理名' %>
      <%= f.submit '検索' %>
    <% end %>
  </div>
    <div class="row">
      <table>
        <thead>
          <tr>
            <th>レシピ名検索結果一覧</th>
          </tr>
        </thead>
        <tbody>
          <tr class="col-lg-4">
            <% @recipes.each do |recipe| %>
              <td>
                <%= link_to recipe_path(recipe.id) do %>
                  <%= attachment_image_tag recipe, :dish_photo, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg", size:'300x300' %>
                <% end %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
</div>

app/views/users/show.html.erb
<!--マイページ-->
<div class="container">
  <div class="row">
    <table class="table table-bordered mt-3">
      <tr>
        <td>
          会員ID
        </td>
        <td>
          <%= @user.id %>
        </td>
      </tr>

      <tr>
        <td>
          名前
        </td>
        <td>
          <%= @user.name %>
        </td>
      </tr>

      <tr>
        <td>
          メールアドレス
        </td>
        <td>
          <%= @user.email %>
        </td>
      </tr>
    </table>
  </div>

  <div class="row">
    <p><%=link_to "フォロー", follows_user_path(@user.id), class: "mt-3 ml-3 mb-3 btn btn-primary" %></p>
    <p><%=link_to "フォロワー", followers_user_path(@user.id), class: "mt-3 ml-3 mb-3 btn btn-primary" %></p>
  </div>

  <div class="row mt-3">
    <% @recipes.each do |recipe| %>
      <div class="col-lg-4">
        <%= link_to recipe_path(recipe.id) do %>
          <%= attachment_image_tag recipe, :dish_photo, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg", size:'300x300' %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="row mt-3">
    <div class="col-lg-12 text-center">
      <%= link_to "編集する", users_edit_path, class: "ml-3 btn btn-success" %>
      <%= link_to "退会する", users_check_path, class: "ml-3 btn btn-danger" %>
    </div>
  </div>
</div>

app/views/users/withdrawal.html.erb
<div class="container">
  <div class="row">
    <div class=" text-box col-lg-12 mx-auto text-center">
      ご愛好ありがとうございました。
      <br>またのご利用をお待ちしております。</br>
      <br><%= link_to "TOPページへ戻る", root_path, class: "mt-3 ml-3 btn btn-primary" %></br>
    </div>
  </div>
</div>